# Generated by Django 5.0.9 on 2024-09-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время, когда необходимо выполнять привычку')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время рассылки')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('is_enjoyable', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в два дня', 'Раз в два дня'), ('Раз в три дня', 'Раз в три дня'), ('Раз в четыре дня', 'Раз в четыре дня'), ('Раз в пять дней', 'Раз в пять дней'), ('Раз в шесть дней', 'Раз в шесть дней'), ('Раз в неделю', 'Раз в неделю')], default='Раз в день', verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вознаграждение')),
                ('duration', models.DurationField(blank=True, default=None, null=True, verbose_name='Время на выполнение привычки')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак публичности')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
